name: amplify_push_notifications
description: Core Push Notifications Flutter package
version: 0.0.1
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_push_notifications_ios: ">=1.0.0-next.0 <1.0.0-next.1"
  amplify_push_notifications_android: ">=1.0.0-next.0 <1.0.0-next.1"
  amplify_secure_storage: ^0.1.0
  amplify_core: ">=1.0.0-next.0 <1.0.0-next.1"

dev_dependencies:
  amplify_lints: ^2.0.0
  amplify_test:
    path: ../../../amplify_test
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: amplify_push_notifications_android
      ios:
        default_package: amplify_push_notifications_ios
