name: Test Log Calls
on: push
jobs:
  testLogMetric:
    runs-on: macos-latest

    # MUST HAVE THIS (check other calls)
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
        with:
          persist-credentials: false
          submodules: true

      - name: Test Wrapper Call
        if: always()
        uses: ./.github/composite_actions/log_metric_wrapper
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          job-status: ${{ job.status }}
          job-identifier: build (${{ matrix.channel }}, ${{ matrix.flutter-version}})
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-type: canary
          category: all
          workflow-name: amplify_canaries/build
          framework: flutter
          flutter-dart-channel: beta
          flutter-version: stable
          platform: android
          platform-version: 14.5
