name: Amplify Canaries
on: push

# Cancels in-progress job when there is another push to same ref.
# h ttps://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Ensure an app pulling in published Amplify libraries can build properly
  build:
    runs-on: macos-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        channel:
          - "beta"
          - "stable"
        flutter-version:
          - "any" # latest
        include:
          - channel: "stable"
            flutter-version: "3.10.1"
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
        with:
          persist-credentials: false
      - name: Log success/failure
        if: always()
        uses: ./.github/composite_actions/log_cw_metric_wrapper
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

          job-status: ${{ job.status }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          test-type: canary
          package-name: amplify_canaries

          framework: flutter
          flutter-dart-channel: ${{ matrix.channel }}
          flutter-version: ${{ matrix.flutter-version }}
