name: Amplify Canaries
on:
  push:
    branches:
      - main
      - stable
      - feat/**
      - fix/**
      - test/**
  pull_request:
    paths:
      - ".github/workflows/amplify_canaries.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Ensure an app pulling in published Amplify libraries can build properly
  build:
    runs-on: macos-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        channel:
          - "beta"
          - "stable"
        flutter-version:
          - "any" # latest
        include:
          - channel: "stable"
            flutter-version: "3.10.1"
    
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # 3.5.3
        with:
          persist-credentials: false          

      - name: Install dependencies
        uses: ./.github/composite_actions/install_dependencies
        with:
          channel: ${{ matrix.channel }}
          flutter-version: ${{ matrix.flutter-version }}

      - name: Log success/failure
        if: always()
        uses: ./.github/composite_actions/log_metric
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}     
          github-token: ${{ secrets.GH_TOKEN }}    
          isFailed: ${{ job.status == 'failure' }}
          testType: canary
          category: all
          workflowName: amplify_canaries/build
          framework: flutter
          flutterDartChannel: ${{ matrix.channel }}
          flutterVersion: $${{ matrix.flutter-version }}

  