name: Test ME
on: push
jobs:
  test:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: Install dependencies
        uses: ./.github/composite_actions/install_dependencies

      - name: Configure AWS credentials
        if: env.SKIP != 'true'
        uses: aws-actions/configure-aws-credentials@04b98b3f9e85f563fb061be8751a0352327246b0 # 3.0.1
        with:
          unset-current-credentials: true
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-duration-seconds: 900

      - name: Change to Dart script directory
        if: env.SKIP != 'true'
        run: cd ./tool
        shell: bash

      - name: Install Dart dependencies (args)
        if: env.SKIP != 'true'
        run: dart pub get
        shell: bash

      # THIS IS WORKING
      # ACCESSIBLE VIA "$FAILING_STEP" or ${{ env.FAILING_STEP }}
      - name: Get Failing Step
        run: |
          dart ./tool/get_failing_step.dart \
            --job-status "failure" \
            --substring "e2e-android (stable, any)" \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --repo "fjnoyp/amplify-flutter" \
            --run-id "6038852014" > dart_output.txt
          echo FAILING_STEP=$(cat dart_output.txt) >> $GITHUB_ENV
        shell: bash

      - name: Run Dart script
        if: env.SKIP != 'true'
        run: |
          dart ./tool/send_metric_data.dart \
            --metric-name="github_metric_1.0" \
            --is-failed="${{ 'failure' == 'failure' }}" \
            --test-type="${{ 'unit test' }}" \
            --category="${{ 'storage' }}" \
            --workflow-name="${{ 'amplify_storage_s3_example/flutter_vm' }}" \
            --framework="${{ 'dart' }}" \
            --flutter-dart-channel="${{ 'dart'}}" \          
            --failing-step="${{ env.FAILING_STEP }}"
        shell: bash
